# Generated by Django 5.2.6 on 2026-05-17 04:52

import django.db.models.deletion
import quotations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent to Client'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=11.0, help_text='PPN %', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='IDR', max_length=5)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('freight', 'Main Freight'), ('trucking', 'Trucking'), ('customs', 'Customs & Clearance'), ('handling', 'Handling & THC'), ('insurance', 'Insurance'), ('other', 'Other Charges')], default='freight', max_length=20)),
                ('charge_name', models.CharField(help_text='e.g., Ocean Freight, Origin THC, BAF', max_length=255)),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit', models.CharField(default='Lot', help_text='e.g., KG, CBM, Container, Lot', max_length=30)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='IDR', max_length=5)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotations.quotation')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(default=quotations.models.generate_ref, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Review'), ('QUOTED', 'Quoted'), ('ACCEPTED', 'Accepted'), ('REVISED', 'Revision Requested'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('mode', models.CharField(choices=[('sea', 'Sea Freight'), ('air', 'Air Freight'), ('land', 'Land Trucking')], max_length=5)),
                ('scope', models.CharField(choices=[('d2d', 'Door to Door'), ('d2p', 'Door to Port / Door to Airport'), ('p2p', 'Port to Port / Airport to Airport'), ('p2d', 'Port to Door / Airport to Door')], max_length=5)),
                ('sea_type', models.CharField(blank=True, choices=[('FCL', 'FCL – Full Container Load'), ('LCL', 'LCL – Less than Container Load')], max_length=5, null=True)),
                ('pol', models.CharField(blank=True, help_text='Port/Airport code e.g. IDTPP, CGK', max_length=20, null=True)),
                ('pol_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pickup_city', models.CharField(blank=True, max_length=255, null=True)),
                ('pickup_address', models.TextField(blank=True, help_text='Full street address for trucking pickup', null=True)),
                ('pickup_country', models.CharField(blank=True, default='Indonesia', max_length=100, null=True)),
                ('pod', models.CharField(blank=True, help_text='Port/Airport code e.g. SGSIN, SIN', max_length=20, null=True)),
                ('pod_name', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_city', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_address', models.TextField(blank=True, help_text='Full street address for trucking delivery', null=True)),
                ('delivery_country', models.CharField(blank=True, max_length=100, null=True)),
                ('shipper_same_as_client', models.BooleanField(default=True)),
                ('shipper_company', models.CharField(blank=True, max_length=255, null=True)),
                ('shipper_address', models.TextField(blank=True, null=True)),
                ('shipper_pic', models.CharField(blank=True, max_length=150, null=True)),
                ('shipper_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('shipper_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('consignee_same_as_client', models.BooleanField(default=False)),
                ('consignee_company', models.CharField(blank=True, max_length=255, null=True)),
                ('consignee_address', models.TextField(blank=True, null=True)),
                ('consignee_pic', models.CharField(blank=True, max_length=150, null=True)),
                ('consignee_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('consignee_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('commodity', models.CharField(max_length=255)),
                ('hs_code', models.CharField(blank=True, max_length=20, null=True)),
                ('is_dangerous', models.BooleanField(default=False)),
                ('dg_class', models.CharField(blank=True, help_text='IMDG/IATA DG class if dangerous', max_length=50, null=True)),
                ('incoterms', models.CharField(blank=True, help_text='e.g., EXW, FOB, CIF, DAP, DDP', max_length=10, null=True)),
                ('cargo_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cargo_currency', models.CharField(default='USD', max_length=5)),
                ('target_etd', models.DateField(blank=True, help_text='Preferred departure date', null=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('container_size', models.CharField(blank=True, max_length=20, null=True)),
                ('container_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('container_weight', models.DecimalField(blank=True, decimal_places=2, help_text='KG per container', max_digits=10, null=True)),
                ('package_type', models.CharField(blank=True, max_length=50, null=True)),
                ('package_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Total KG', max_digits=10, null=True)),
                ('volume_cbm', models.DecimalField(blank=True, decimal_places=3, help_text='Total CBM', max_digits=10, null=True)),
                ('dimensions', models.JSONField(blank=True, help_text='[{l, w, h, qty}]', null=True)),
                ('is_stackable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales_in_charge', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['ADMIN', 'SALES']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_requests', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quotation Request',
                'verbose_name_plural': 'Quotation Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='quotation',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quotation', to='quotations.quotationrequest'),
        ),
    ]
