# Generated by Django 5.2.6 on 2026-05-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='discount_type',
            field=models.CharField(choices=[('AMOUNT', 'Fixed Amount'), ('PERCENT', 'Percentage (%)')], default='AMOUNT', max_length=10),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='land_dest_type',
            field=models.CharField(blank=True, choices=[('residence', 'Residence'), ('business', 'Business Address / Office'), ('warehouse', 'Warehouse / Factory')], help_text='Only for Land Trucking mode', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='land_origin_type',
            field=models.CharField(blank=True, choices=[('residence', 'Residence'), ('business', 'Business Address / Office'), ('warehouse', 'Warehouse / Factory')], help_text='Only for Land Trucking mode', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount amount (or % value if discount_type=PERCENT)', max_digits=14),
        ),
    ]
