# Generated by Django 5.2.6 on 2026-05-19 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_add_land_point_type_and_discount_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationRequestCargoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_size', models.CharField(blank=True, max_length=20, null=True)),
                ('container_qty', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('container_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Berat per kontainer dalam KG', max_digits=10, null=True)),
                ('package_type', models.CharField(blank=True, max_length=50, null=True)),
                ('package_qty', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Total KG untuk baris ini', max_digits=10, null=True)),
                ('volume_cbm', models.DecimalField(blank=True, decimal_places=3, help_text='Total CBM untuk baris ini', max_digits=10, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, help_text='Panjang dalam cm', max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, help_text='Lebar dalam cm', max_digits=10, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Tinggi dalam cm', max_digits=10, null=True)),
                ('is_stackable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quotation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_items', to='quotations.quotationrequest')),
            ],
            options={
                'verbose_name': 'Quotation Request Cargo Item',
                'verbose_name_plural': 'Quotation Request Cargo Items',
                'ordering': ['id'],
            },
        ),
    ]
