# Generated by Django 5.2.6 on 2026-05-22 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_quotationrequestcargoitem'),
        ('users', '0003_tenant_user_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='users.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_items', to='users.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_requests', to='users.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotationrequestcargoitem',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cargo_items', to='users.tenant'),
            preserve_default=False,
        ),
    ]
