# Generated by Django 5.2.6 on 2026-06-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0006_charge_master_and_price_lock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationrequest',
            name='status',
            field=models.CharField(choices=[('INQUIRY', 'Inquiry'), ('ASSIGNED', 'Assigned'), ('QUOTED', 'Quoted'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='INQUIRY', max_length=20),
        ),
    ]
