# Generated by Django 5.2.6 on 2026-06-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0007_alter_quotationrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargemaster',
            name='is_tax',
            field=models.BooleanField(default=False, help_text='If True, this charge is a tax item (PPN/PPh etc.)'),
        ),
        migrations.AddField(
            model_name='chargemaster',
            name='tax_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tax percentage (e.g. 1.10 for 1.1%). Used when is_tax=True', max_digits=5, null=True),
        ),
    ]
