# Generated by Django 5.2.6 on 2026-06-04 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0008_chargemaster_is_tax_chargemaster_tax_percent'),
        ('users', '0008_clientprofile_preferred_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='is_taxable',
            field=models.BooleanField(default=True, help_text='If True, this item is subject to selected taxes below'),
        ),
        migrations.CreateModel(
            name='TaxMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('code', models.CharField(help_text='e.g. VAT1, VAT2', max_length=20)),
                ('display', models.CharField(help_text='e.g. VAT', max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Percentage (e.g. 1.10 for 1.1%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_masters', to='users.tenant')),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='taxes',
            field=models.ManyToManyField(blank=True, help_text='Which tax(es) apply to this item', to='quotations.taxmaster'),
        ),
        migrations.AddConstraint(
            model_name='taxmaster',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_tax_code_per_tenant'),
        ),
    ]
