# Generated by Django 5.2.6 on 2026-06-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0009_alter_quotationitem_is_taxable_taxmaster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargemaster',
            name='default_taxes',
            field=models.ManyToManyField(blank=True, help_text='Tax(es) that apply by default when this charge is selected', to='quotations.taxmaster'),
        ),
    ]
