# Generated by Django 5.2.6 on 2026-05-22 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_tenant_user_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('SEA', 'Sea Freight'), ('AIR', 'Air Freight'), ('LAND', 'Land/Trucking')], max_length=10)),
                ('scope', models.CharField(choices=[('D2D', 'Door to Door'), ('D2P', 'Door to Port'), ('P2D', 'Port to Door'), ('P2P', 'Port to Port')], max_length=10)),
                ('origin_type', models.CharField(choices=[('PORT', 'Seaport'), ('AIRPORT', 'Airport'), ('CITY', 'City'), ('ADDRESS', 'Specific Address')], max_length=10)),
                ('origin_name', models.CharField(help_text='Port/Airport/City name', max_length=255)),
                ('origin_address', models.TextField(blank=True, help_text='Full address for Door', null=True)),
                ('destination_type', models.CharField(choices=[('PORT', 'Seaport'), ('AIRPORT', 'Airport'), ('CITY', 'City'), ('ADDRESS', 'Specific Address')], max_length=10)),
                ('destination_name', models.CharField(max_length=255)),
                ('destination_address', models.TextField(blank=True, null=True)),
                ('container_type', models.CharField(blank=True, choices=[('20GP', '20ft General Purpose'), ('40GP', '40ft General Purpose'), ('40HC', '40ft High Cube'), ('LCL', 'Less than Container Load')], max_length=10, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('IDR', 'Indonesian Rupiah'), ('USD', 'US Dollar')], default='IDR', max_length=3)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, help_text='Leave blank for indefinite', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this tariff')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tariffs_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Which 3PL company owns this tariff', on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='users.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mode', 'scope', 'is_active'], name='tariffs_tar_mode_d53ffe_idx'), models.Index(fields=['origin_name', 'destination_name'], name='tariffs_tar_origin__2ad02a_idx')],
            },
        ),
    ]
