# Generated by Django 5.2.6 on 2026-05-24 01:42

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('kind', models.CharField(choices=[('country', 'Country'), ('province', 'Province'), ('regency', 'Regency / Kabupaten'), ('city-admin', 'City Administrative / Kota'), ('district', 'District / Kecamatan'), ('locality', 'Locality / Kelurahan'), ('city', 'City (General)'), ('airport', 'Airport'), ('port', 'Sea Port'), ('jetty', 'Jetty'), ('anchorage', 'Anchorage'), ('train-station', 'Train Station'), ('bus-terminal', 'Bus Terminal'), ('warehouse', 'Warehouse / Depot')], max_length=20)),
                ('iata_code', models.CharField(blank=True, help_text='IATA code (airports)', max_length=10, null=True)),
                ('unlocode', models.CharField(blank=True, help_text='UN/LOCODE (sea ports)', max_length=10, null=True)),
                ('iso_code', models.CharField(blank=True, help_text='ISO 3166-2', max_length=20, null=True)),
                ('country_code', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2', max_length=2, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='locations.location')),
            ],
            options={
                'db_table': 'locations_location',
                'indexes': [models.Index(fields=['code'], name='loc_code_idx'), models.Index(fields=['kind'], name='loc_kind_idx'), models.Index(fields=['iata_code'], name='loc_iata_idx'), models.Index(fields=['unlocode'], name='loc_unlocode_idx'), models.Index(fields=['country_code'], name='loc_country_idx'), models.Index(fields=['kind', 'name'], name='loc_kind_name_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('latitude__isnull', True), models.Q(('latitude__gte', -90), ('latitude__lte', 90)), _connector='OR'), name='chk_lat_range'), models.CheckConstraint(condition=models.Q(('longitude__isnull', True), models.Q(('longitude__gte', -180), ('longitude__lte', 180)), _connector='OR'), name='chk_lng_range')],
            },
        ),
    ]
