# Generated by Django 5.2.6 on 2026-05-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='IATA/UN LOCODE, e.g. IDTPP, CGK', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Full port/airport name', max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Indonesia', max_length=100)),
                ('country_code', models.CharField(default='ID', max_length=3)),
                ('port_type', models.CharField(choices=[('SEA', 'Sea Port'), ('AIR', 'Airport')], max_length=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Port / Airport',
                'verbose_name_plural': 'Ports / Airports',
                'ordering': ['country_code', 'port_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Indonesia', max_length=100)),
                ('country_code', models.CharField(default='ID', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['country_code', 'province', 'name'],
                'unique_together': {('name', 'province', 'country_code')},
            },
        ),
    ]
