# Generated by Django 5.2.6 on 2026-05-22 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
        ('users', '0003_tenant_user_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='users.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipmentdocument',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shipment_documents', to='users.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipmentmilestone',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shipment_milestones', to='users.tenant'),
            preserve_default=False,
        ),
    ]
