# Generated by Django 5.2.6 on 2026-05-23 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_shipment_tenant_shipmentdocument_tenant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ['-created_at']},
        ),
    ]
