# Generated by Django 5.2.6 on 2026-05-17 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='nib_siup',
            field=models.CharField(blank=True, help_text='NIB / SIUP', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='client_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual / Personal'), ('business', 'Business / SME'), ('corporate', 'Corporate / Enterprise')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_level',
            field=models.IntegerField(choices=[(1, 'Basic — Account Created'), (2, 'Verified — Documents Submitted'), (3, 'Trusted — Partner Approved')], default=1),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_id',
            field=models.CharField(blank=True, help_text='NPWP', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.company'),
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=30, null=True)),
                ('position', models.CharField(blank=True, help_text='Job title / position', max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(default='Indonesia', max_length=100)),
                ('id_type', models.CharField(blank=True, choices=[('ktp', 'KTP (Indonesia)'), ('passport', 'Passport'), ('other', 'Other Government ID')], max_length=10, null=True)),
                ('id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('company_email', models.EmailField(blank=True, help_text='Official company email (may differ from login)', max_length=254, null=True)),
                ('npwp', models.CharField(blank=True, max_length=30, null=True)),
                ('nib_siup', models.CharField(blank=True, max_length=50, null=True)),
                ('kyc_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('kyc_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('kyc_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kyc_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
