# Generated by Django 5.2.6 on 2026-05-22 01:12

import django.db.models.deletion
from django.db import migrations, models


def create_default_tenant(apps, schema_editor):
    """Create default tenant for existing data."""
    Tenant = apps.get_model('users', 'Tenant')
    Tenant.objects.create(
        id=1,
        name='PT. Kargopath Logistic Nusantara',
        slug='kargopath-logistic',
        contact_email='info@kargopath.com',
        contact_phone='',
        primary_color='#2563eb',
        is_active=True,
    )


def reverse_default_tenant(apps, schema_editor):
    """Remove default tenant on migration rollback."""
    Tenant = apps.get_model('users', 'Tenant')
    Tenant.objects.filter(id=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_company_nib_siup_company_website_user_client_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company name', max_length=255)),
                ('slug', models.SlugField(help_text='URL-safe identifier (for subdomain)', unique=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenant_logos/')),
                ('primary_color', models.CharField(default='#2563eb', help_text='Hex color code', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['name'],
            },
        ),
        # Create default tenant before adding foreign keys
        migrations.RunPython(
            create_default_tenant,
            reverse_default_tenant,
        ),
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(default=1, help_text='Which 3PL company this user belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.tenant'),
            preserve_default=False,
        ),
    ]
