# Generated by Django 5.2.6 on 2026-05-28 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_update_client_type_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='qr_date_format',
            field=models.CharField(choices=[('YYMM', 'YY-MM (e.g., 2605)'), ('MMYY', 'MM-YY (e.g., 0526)')], default='YYMM', max_length=4),
        ),
        migrations.AddField(
            model_name='tenant',
            name='qr_prefix',
            field=models.CharField(default='Q', help_text='Max 3 uppercase letters', max_length=3),
        ),
        migrations.AddField(
            model_name='tenant',
            name='qr_seq_length',
            field=models.IntegerField(choices=[(4, '4 digits'), (5, '5 digits'), (6, '6 digits')], default=4),
        ),
    ]
