# Generated by Django 5.2.6 on 2026-05-28 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_tenant_qr_date_format_tenant_qr_prefix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='currencies',
            field=models.JSONField(default=list, help_text="List of enabled currencies, e.g., ['IDR', 'USD']"),
        ),
        migrations.AddField(
            model_name='tenant',
            name='default_discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage (%)'), ('nominal', 'Nominal')], default='percentage', max_length=15),
        ),
        migrations.AddField(
            model_name='tenant',
            name='default_discount_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='tenant',
            name='default_tax_rate',
            field=models.DecimalField(decimal_places=2, default=11.0, help_text='Default Tax/PPN %', max_digits=5),
        ),
        migrations.AddField(
            model_name='tenant',
            name='invoice_terms',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tenant',
            name='quotation_agreement',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tenant',
            name='service_level_agreement',
            field=models.TextField(blank=True, default=''),
        ),
    ]
