# Generated by Django 5.2.6 on 2026-05-28 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_tenant_currencies_tenant_default_discount_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='invoice_terms',
            new_name='booking_terms',
        ),
    ]
