# Generated by Django 5.2.6 on 2026-06-03 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_invoice_terms_tenant_booking_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='preferred_currency',
            field=models.CharField(choices=[('IDR', 'IDR — Indonesian Rupiah'), ('USD', 'USD — US Dollar'), ('SGD', 'SGD — Singapore Dollar'), ('MYR', 'MYR — Malaysian Ringgit'), ('CNY', 'CNY — Chinese Yuan'), ('JPY', 'JPY — Japanese Yen'), ('EUR', 'EUR — Euro'), ('GBP', 'GBP — British Pound'), ('AUD', 'AUD — Australian Dollar')], default='IDR', help_text="Client's preferred transaction currency", max_length=5),
        ),
    ]
